var bingoList = [];
bingoList[1] = [
    { name: "ハイリアのフード", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "ハイリアの服", types: ["Clothes","Hylian Gear","Rupee","Rupee"] },
    { name: "防寒着", types: ["Clothes","Cold Resistance","Hateno"] },
    { name: "始まりの台地のコログのミ3つ", types: ["Korok","Plateau"] },
    { name: "ハイリアのズボン", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "”ボコ”と名のついた装備", types: ["Equipment"] },
    { name: "双子山の塔のコログのミ3つ", types: ["Korok","Dueling Peaks"] },
    { name: "平原の塔のコログのミ3つ", types: ["Korok","Central Hyrule"] }
];
bingoList[2] = [
    { name: "コログのミ5つ", types: ["Korok"] },
    { name: "ハテノの塔のコログのミ3つ", types: ["Korok","Hateno"] },
    { name: "フィローネの塔のコログのミ3つ", types: ["Korok","Faron"] },
    { name: "丘陵の塔のコログのミ3つ", types: ["Korok","Ridgeland"] },
    { name: "”錆びた”と名のついた装備", types: ["Equipment"] },
    { name: "”がんばり”効果の料理", types: ["Cooking","Stamina"] },
    { name: "テリーにカブトムシを渡す", types: ["Horse"] },
    { name: "馬を登録する", types: ["Horse"] },
    { name: "コッコを怒らせる", types: ["Cucco"] },
    { name: "双子山の塔を起動させる", types: ["Tower","Dueling Peaks"] },
    { name: "木のオタマ", types: ["Equipment"] },
    { name: "ミニチャレンジ:ココナ'sキッチン1", types: ["Side Quest","Dueling Peaks"] },
    { name: "”ゴーゴー”効果の料理", types: ["Cooking"] },
    { name: "”ピリ辛”効果の料理", types: ["Cooking","Cold Resistance"] }
];
bingoList[3] = [
    { name: "始まりの台地のコログのミ5つ", types: ["Korok","Plateau"] },
    { name: "双子山の塔のコログのミ6つ", types: ["Korok","Dueling Peaks"] },
    { name: "湖の塔のコログのミ3つ", types: ["Korok","Lake"] },
    { name: "荒野の塔のコログのミ3つ", types: ["Korok","Wasteland"] },
    { name: "森林の塔のコログのミ3つ", types: ["Korok","Woodland"] },
    { name: "ラネールの塔のコログのミ3つ", types: ["Korok","Lanayru"] },
    { name: "ミニチャレンジ:大事なマラカス", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:プリコと遊ぼ！", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:野生馬を捕まえて", types: ["Side Quest","Dueling Peaks","Horse"] },
    { name: "ミニチャレンジ:器の操者", types: ["Side Quest","Hateno"] },
    { name: "ほこらチャレンジ:花を踏まないで", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "”スタミナ”効果の料理", types: ["Cooking","Stamina"] },
    { name: "”チカラ”効果の料理", types: ["Cooking"] },
    { name: "”しのび”効果の料理", types: ["Cooking"] },
    { name: "微妙な料理", types: ["Cooking"] },
    { name: "ボコブリンキャンプの宝箱を2つ", types: ["Plateau"] },
    { name: "襲われている旅人を助ける", types: ["Monster"] },
    { name: "湖の塔を起動させる", types: ["Tower","Lake"] },
    { name: "タバンタの塔のコログのミを3つ", types: ["Korok","Tabantha"] },
    { name: "スタル系の骨", types: ["Equipment"] },
    { name: "ミニチャレンジを3つクリア", types: ["Side Quest"] }
];
bingoList[4] = [
    { name: "コログのミ10個", types: ["Korok"] },
    { name: "オルディンの塔のコログのミ3つ", types: ["Korok","Eldin"] },
    { name: "アッカレの塔のコログのミ3つ", types: ["Korok","Akkala"] },
    { name: "大妖精を1人解放", types: ["Rupee","Great Fairy"] },
    { name: "ハイリアの装備一式", types: ["Clothes","Hylian Gear","Rupee"] },
    { name: "ハイリア兵の兜", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "ハイリア兵の鎧", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "ハイリア兵のすねあて", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "忍びマスク", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "忍びタイツ", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "クライムバンダナ", types: ["Clothes","Climbing Gear","Dueling Peaks"] },
    { name: "ミニチャレンジ:消えたコッコちゃん", types: ["Side Quest","Dueling Peaks","Heirloom"] },
    { name: "ミニチャレンジ:ココナ'sキッチン2", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:燃える矢じりで貫いて", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:新妻は花よりダンゴ", types: ["Side Quest","Tabantha"] },
    { name: "力の試練 序位の祠をクリア", types: ["Shrine","Guardian"] },
    { name: "畑のクワ", types: ["Equipment"] },
    { name: "”マックス”効果の料理", types: ["Cooking"] },
    { name: "”カチコチ”効果の料理", types: ["Cooking"] },
    { name: "マックス薬", types: ["Cooking"] },
    { name: "がんばり薬", types: ["Cooking"] },
    { name: "ひんやり薬", types: ["Cooking"] },
    { name: "ゴーゴー薬", types: ["Cooking"] },
    { name: "スタミナ薬", types: ["Cooking"] },
    { name: "チカラ薬", types: ["Cooking"] },
    { name: "カチコチ薬", types: ["Cooking"] },
    { name: "しのび薬", types: ["Cooking"] },
    { name: "硬すぎ料理", types: ["Cooking"] },
    { name: "ウィズローブを倒す", types: ["Wizzrobe"] },
    { name: "イワロックを倒す", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "イワロック（無印）を倒す", types: ["Rupee","Gems","Miniboss","Talus"] },
    { name: "朽ちたガーディアンを倒す", types: ["Miniboss","Guardian"] },
    { name: "鹿に乗る", types: ["Horse"] },
    { name: "紫ルピー", types: ["Rupee"] },
    { name: "パーヤの日記を読む", types: ["Dueling Peaks"] },
    { name: "プルアの日記を読む", types: ["Hateno"] },
    { name: "ハテノの塔を起動する", types: ["Tower","Hateno"] },
    { name: "フィローネの塔を起動する", types: ["Tower","Faron"] },
    { name: "荒野の塔を起動する", types: ["Tower","Wasteland"] },
    { name: "丘陵の塔を起動する", types: ["Tower","Ridgeland"] },
    { name: "ミニチャレンジを4つ", types: ["Side Quest"] },
    { name: "ロッド系の武器", types: ["Equipment","Wizzrobe"] }
];
bingoList[5] = [
    { name: "ハテノの塔のコログのミ6つ", types: ["Korok","Hateno"] },
    { name: "フィローネの塔のコログのミ6つ", types: ["Korok","Faron"] },
    { name: "湖の塔のコログのミ6つ", types: ["Korok","Lake"] },
    { name: "荒野の塔のコログのミ6つ", types: ["Korok","Wasteland"] },
    { name: "ゲルドの塔のコログのミ3つ", types: ["Korok","Gerudo"] },
    { name: "丘陵の塔のコログのミ6つ", types: ["Korok","Ridgeland"] },
    { name: "ヘブラの塔のコログのミ3つ", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "森林の塔のコログのミ6つ", types: ["Korok","Woodland"] },
    { name: "ラネールの塔のコログのミ6つ", types: ["Korok. Lanayru"] },
    { name: "平原の塔のコログのミ6つ", types: ["Korok","Central Hyrule"] },
    { name: "ラバーキャップ", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "ラバースーツ", types: ["Clothes","Rubber Gear","Ridgeland"] },
    { name: "ラバータイツ", types: ["Clothes","Rubber Gear","Faron"] },
    { name: "忍びスーツ", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "ミニチャレンジ:大盗賊ラムダの財宝", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:海に沈んだ財宝", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:勇者の蓄え？", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:雷怖い", types: ["Side Quest","Faron","Rubber Gear"] },
    { name: "ミニチャレンジ:その馬 買い取ります！", types: ["Side Quest","Wasteland","Horse"] },
    { name: "ミニチャレンジ:新郎の汚名返上", types: ["Side Quest","Tabantha"] },
    { name: "ミニチャレンジ:大妖精さまのおふせ", types: ["Side Quest","Tabantha","Rupee","Great Fairy"] },
    { name: "ミニチャレンジ:風船よ舞い上がれ！", types: ["Side Quest","Woodland"] },
    { name: "ミニチャレンジ:水底に沈むお宝", types: ["Side Quest","Central Hyrule"] },
    { name: "ほこらチャレンジ:ふたつの輪", types: ["Shrine","Shrine Quest","Ridgeland"] },
    { name: "ブーメラン系の武器", types: ["Equipment"] },
    { name: "”リザルフォス”と名の付いた装備", types: ["Equipment"] },
    { name: "船のオール", types: ["Equipment"] },
    { name: "”モリブリン”と名の付いた装備", types: ["Equipment"] },
    { name: "木のモップ", types: ["Equipment"] },
    { name: "”ピリ辛”効果の料理", types: ["Cooking","Wasteland"] },
    { name: "”エレキ”効果の料理", types: ["Cooking"] },
    { name: "ピリ辛薬", types: ["Cooking"] },
    { name: "エレキ薬", types: ["Cooking"] },
    { name: "ファイアーウィズローブを倒す", types: ["Wizzrobe"] },
    { name: "エレキウィズローブを倒す", types: ["Wizzrobe"] },
    { name: "ヒノックスを倒す", types: ["Miniboss","Hinox"] },
    { name: "レッドヒノックスを倒す", types: ["Miniboss","Hinox"] },
    { name: "鳥人間コンテストで500m飛ぶ", types: ["Minigame","Ridgeland"] },
    { name: "ラネールの塔を起動する", types: ["Tower","Lanayru"] },
    { name: "平原の塔を起動する", types: ["Tower","Central Hyrule"] }
];
bingoList[6] = [
    { name: "タバンタの塔のコログのミ6つ", types: ["Korok","Tabantha"] },
    { name: "アッカレの塔のコログのミ6つ", types: ["Korok","Akkala"] },
    { name: "淑女の装備一式", types: ["Clothes","Wasteland","Rupee"] },
    { name: "赤色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "黄色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "紫色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "緑色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "薄黄色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "灰色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:ココナ'sキッチン3", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:しのび草の君", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:馬に乗った荒くれ者", types: ["Side Quest","Lake"] },
    { name: "ミニチャレンジ:王家の白馬", types: ["Side Quest","Central Hyrule","Horse","Stamina"] },
    { name: "ほこらチャレンジ:呪われし石像", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "漁師のモリ", types: ["Equipment"] },
    { name: "同じ武器3つ", types: ["Equipment"] },
    { name: "燃えずの薬", types: ["Cooking"] },
    { name: "ゆでタマゴ", types: ["Cooking"] },
    { name: "アイスウィズローブを倒す", types: ["Wizzrobe"] },
    { name: "銀ルピー", types: ["Rupee"] },
    { name: "タバンタの塔を起動する", types: ["Tower","Tabantha"] },
    { name: "森林の塔を起動する", types: ["Tower","Woodland"] }
];
bingoList[7] = [
    { name: "コログのミ15個", types: ["Korok"] },
    { name: "リトの羽毛服", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "リトの羽毛ズボン", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "ゾーラの兜", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "ゾーラの鎧", types: ["Clothes","Zora Gear","Lanayru"] },
    { name: "青色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "白色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "薄青色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "橙色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "深紅色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "茶色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:ココナ'sキッチン4", types: ["Side Quest","Dueling Peaks"] },
    { name: "ミニチャレンジ:にっくきヒツジ泥棒", types: ["Side Quest","Hateno"] },
    { name: "ミニチャレンジ:暑さをしのぐ薬", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:飛び込みに目覚めた男", types: ["Side Quest","Lanayru"] },
    { name: "双子山の塔の祠3つクリア", types: ["Shrine","Dueling Peaks"] },
    { name: "ほこらチャレンジ:二本槍の獣", types: ["Shrine","Shrine Quest","Hateno","Horse"] },
    { name: "ほこらチャレンジ:馬宿の風景画", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "”ゾーラ”と名の付いた装備", types: ["Equipment"] },
    { name: "アイス属性の装備", types: ["Equipment"] },
    { name: "妖精の力水", types: ["Cooking"] },
    { name: "甘露煮肉", types: ["Cooking"] },
    { name: "岩塩焼きガニ", types: ["Cooking"] },
    { name: "がんばりの器2つ", types: ["Shrine","Stamina"] },
    { name: "ロベリーの日記を読む", types: ["Akkala"] },
    { name: "ゲルドの塔を起動する", types: ["Tower","Gerudo"] },
    { name: "オルディンの塔を起動する", types: ["Tower","Eldin"] }
];
bingoList[8] = [
    { name: "始まりの台地のコログのミを7つ", types: ["Korok","Plateau"] },
    { name: "双子山の塔のコログのミ9つ", types: ["Korok","Dueling Peaks"] },
    { name: "ハテノの塔のコログのミ9つ", types: ["Korok","Hateno"] },
    { name: "湖の塔のコログのミ9つ", types: ["Korok","Lake"] },
    { name: "ゲルドの塔のコログのミ6つ", types: ["Korok","Gerudo"] },
    { name: "ヘブラの塔のコログのミ6つ", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンの塔のコログのミ6つ", types: ["Korok","Eldin"] },
    { name: "平原の塔のコログのミ9つ", types: ["Korok","Central Hyrule"] },
    { name: "ハイリアのフード ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリアの服 ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリアのズボン ★", types: ["Clothes","Hylian Gear","Rupee","Great Fairy","Bokoblin"] },
    { name: "ハイリア兵の装備一式", types: ["Clothes","Soldier Gear","Rupee","Hateno"] },
    { name: "雪よけの羽飾り", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "耐火の石鎧", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "耐火の石靴", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "黒色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "紺色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "桃色に染めたハイリアのフード", types: ["Clothes","Hylian Gear","Hateno"] },
    { name: "ミニチャレンジ:こおりの杖のしれん", types: ["Side Quest","Woodland","Wizzrobe"] },
    { name: "湖の塔の祠3つクリア", types: ["Shrine","Lake"] },
    { name: "平原の塔の祠3つクリア", types: ["Shrine","Central Hyrule"] },
    { name: "ほこらチャレンジ:風を束ねて制する者よ", types: ["Shrine","Shrine Quest","Lanayru"] },
    { name: "”森人”と名の付いた装備", types: ["Equipment"] },
    { name: "炎属性の武器", types: ["Equipment"] },
    { name: "雷属性の武器", types: ["Equipment"] },
    { name: "ガーディアンランス（+が付いていても可）", types: ["Equipment","Guardian"] },
    { name: "フルーツケーキ", types: ["Cooking"] },
    { name: "山盛串焼き魚", types: ["Cooking"] },
    { name: "ガーディアン（歩行型）を倒す", types: ["Miniboss","Guardian"] },
    { name: "王家の白馬を登録する", types: ["Horse","Central Hyrule","Stamina"] },
    { name: "キルトンと話す", types: ["Kilton","Akkala"] },
    { name: "金ルピー", types: ["Rupee"] },
    { name: "ハートの器5つ", types: ["Shrine","Heart"] },
    { name: "鹿狩りのミニゲームで5体狩る", types: ["Minigame","Hateno"] },
    { name: "ヘブラの塔を起動する", types: ["Tower","Hebra","Cold Resistance"] }
];
bingoList[9] = [
    { name: "フィローネの塔のコログのミ9つ", types: ["Korok","Faron"] },
    { name: "丘陵の塔のコログのミ9つ", types: ["Korok","Ridgeland"] },
    { name: "ラネールの塔のコログのミ9つ", types: ["Korok. Lanayru"] },
    { name: "クライムシューズ", types: ["Clothes","Climbing Gear","Hateno"] },
    { name: "ミニチャレンジ:今日の晩御飯", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:秘密クラブの秘密", types: ["Side Quest","Wasteland","Radiant Gear","Desert Gear"] },
    { name: "ミニチャレンジ:ゲルドキャニオン失踪事件", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:ヒケシトカゲを捕まえて！", types: ["Side Quest","Eldin","Flame Gear"] },
    { name: "丘陵の塔の祠3つクリア", types: ["Shrine","Ridgeland"] },
    { name: "双子の記憶の祠を両方クリア", types: ["Shrine","Shrine Quest","Dueling Peaks"] },
    { name: "ほこらチャレンジ:稲妻が開く試練", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "コログのしれんを1つクリア", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ガーディアンナイフ（＋が付いていても可）", types: ["Equipment","Guardian"] },
    { name: "同じ盾3つ", types: ["Equipment"] },
    { name: "同じ弓3つ", types: ["Equipment"] },
    { name: "アップルパイ", types: ["Cooking","Tabantha"] },
    { name: "カレーピラフ", types: ["Cooking"] },
    { name: "青ヒノックスを倒す", types: ["Miniboss","Hinox"] },
    { name: "ガンガンゴルフをクリアする", types: ["Minigame","Woodland"] },
    { name: "アッカレの塔を起動する", types: ["Tower","Akkala"] },
    { name: "フロドラから素材を入手", types: ["Dragon"] }
];
bingoList[10] = [
    { name: "荒野の塔のコログのミ9つ", types: ["Korok","Wasteland"] },
    { name: "タバンタの塔のコログのミ9つ", types: ["Korok","Tabantha"] },
    { name: "森林の塔のコログのミ9つ", types: ["Korok","Woodland"] },
    { name: "アッカレの塔のコログのミ9つ", types: ["Korok","Akkala"] },
    { name: "クライムバンダナ ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "蛮族の服", types: ["Clothes","Barbarian Gear","Wasteland"] },
    { name: "ミニチャレンジ:奪われた漁場", types: ["Side Quest","Faron"] },
    { name: "ミニチャレンジ:巨大馬捕獲作戦", types: ["Side Quest","Lake","Horse","Stamina"] },
    { name: "フィローネの塔の祠3つクリア", types: ["Shrine","Faron"] },
    { name: "荒野の塔の祠3つクリア", types: ["Shrine","Wasteland"] },
    { name: "力の試練 中位の祠をクリア", types: ["Shrine","Guardian"] },
    { name: "ほこらチャレンジ:三本杉の秘密", types: ["Shrine","Shrine Quest","Hateno"] },
    { name: "ほこらチャレンジ:砂漠の試練", types: ["Shrine","Shrine Quest","Wastelands","Barbarian Gear"] },
    { name: "ほこらチャレンジ:消える？砂嵐", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:渦巻の中心へ", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "ほこらチャレンジ:ドクロの左目", types: ["Shrine","Shrine Quest","Akkala"] },
    { name: "ガーディアンガード（＋が付いていても可）", types: ["Equipment","Guardian"] },
    { name: "キノコミルクスープ", types: ["Cooking"] },
    { name: "雪玉ボウリングを遊ぶ", types: ["Minigame","Hebra","Cold Resistance"] }
];
bingoList[11] = [
    { name: "コログのミ20個", types: ["Korok"] },
    { name: "大妖精を2人解放する", types: ["Rupee","Great Fairy"] },
    { name: "ハイリア兵の鎧 ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "熱砂の鉢がね", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "熱砂のズボン", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "ラバーキャップ ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "忍びマスク ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍びスーツ ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍びタイツ ★", types: ["Clothes","Stealth Gear","Rupee","Great Fairy"] },
    { name: "忍び装備一式", types: ["Clothes","Stealth Gear","Rupee","Dueling Peaks"] },
    { name: "蛮族の兜", types: ["Clothes","Barbarian Gear","Akkala"] },
    { name: "ミニチャレンジ:愛しの人が望む物", types: ["Side Quest","Hateno"] },
    { name: "ハテノの塔の祠3つクリア", types: ["Shrine","Hateno"] },
    { name: "タバンタの塔の祠3つクリア", types: ["Shrine","Tabantha"] },
    { name: "森林の塔の祠3つクリア", types: ["Shrine","Woodland"] },
    { name: "アッカレの塔の祠3つクリア", types: ["Shrine","Akkala"] },
    { name: "ほこらチャレンジ:口を閉ざした剣士", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:雪山の日誌", types: ["Shrine","Shrine Quest","Wastelands","Cold Resistance"] },
    { name: "忘れ去られた神殿の祠をクリア", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ほこらチャレンジ:暗闇の試練", types: ["Shrine","Shrine Quest","Woodland"] },
    { name: "ほこらチャレンジ:ゴロンのド根性ガケ", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "ほこらチャレンジ:孤島の試練", types: ["Shrine","Shrine Quest","Akkala","Barbarian Gear"] },
    { name: "”王家の”と名の付いた装備", types: ["Equipment"] },
    { name: "上のグレードのロッド（メテオ・フリーズ・ボルテージのいずれか）", types: ["Equipment","Wizzrobe"] },
    { name: "ガーディアンアクス（＋が付いていても可）", types: ["Equipment","Guardian"] },
    { name: "マモノケーキ", types: ["Cooking","Kilton"] },
    { name: "イチゴクレープ", types: ["Cooking","Tabantha"] },
    { name: "イワロック（希少）を倒す", types: ["Rupee","Miniboss","Talus"] },
    { name: "巨大馬を登録する", types: ["Horse","Lake","Stamina"] },
    { name: "クマに乗る", types: ["Horse","Stamina"] },
    { name: "スタルホースに乗る", types: ["Horse"] },
    { name: "2000ルピー", types: ["Rupee"] },
    { name: "王の日記を読む", types: ["Hyrule Castle"] },
    { name: "ポックリンとツーショットを撮る", types: ["Dueling Peaks","Camera"] },
    { name: "シーカーセンサー+", types: ["Camera","Rune Upgrade","Hateno"] }
];
bingoList[12] = [
    { name: "双子山の塔のコログのミ12個", types: ["Korok","Dueling Peaks"] },
    { name: "オルディンの塔のコログのミ9つ", types: ["Korok","Eldin"] },
    { name: "平原の塔のコログのミ12個", types: ["Korok","Central Hyrule"] },
    { name: "英傑の服", types: ["Clothes","Champion","Camera"] },
    { name: "ハイリア兵の兜 ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "ハイリア兵のすねあて ★", types: ["Clothes","Soldier Gear","Rupee","Great Fairy"] },
    { name: "熱砂の肩当て", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "ラバーキャップ ★", types: ["Clothes","Rubber Gear","Ridgeland","Great Fairy"] },
    { name: "ラバータイツ ★", types: ["Clothes","Rubber Gear","Faron","Great Fairy"] },
    { name: "ゾーラのすねあて", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "コハクの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:王家秘伝のレシピ", types: ["Side Quest","Central Hyrule","Cooking"] },
    { name: "ほこらチャレンジを2つクリア", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:七人の英雄", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:絶壁の文様", types: ["Shrine","Shrine Quest","Gerudo","Cold Resistance"] },
    { name: "ほこらチャレンジ:影が示す先に", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "記憶を1つ思い出す", types: ["Camera"] },
    { name: "ゼルダの日記を読む", types: ["Hyrule Castle"] },
    { name: "カッシーワとツーショット写真を撮る", types: ["Camera"] },
    { name: "ラネールの塔の祠3つクリア", types: ["Shrine","Lanayru"] },
    { name: "ミニチャレンジ:ウツシエとシーカーセンサー", types: ["Side Quest","Hateno","Camera"] },
    { name: "ミニチャレンジ:ホタル ノ ヒカリ", types: ["Side Quest","Dueling Peaks","Heirloom","Camera"] }
];
bingoList[13] = [
    { name: "ハテノの塔のコログのミ12個", types: ["Korok","Hateno"] },
    { name: "湖の塔のコログのミ12個", types: ["Korok","Lake"] },
    { name: "荒野の塔のコログのミ12個", types: ["Korok","Ridgeland"] },
    { name: "ヘブラの塔のコログのミ9つ", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "耐火の石兜", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "ゾーラの鎧 ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "蛮族の腰巻き", types: ["Clothes","Barbarian Gear","Hebra"] },
    { name: "ヘブラの塔の祠3つクリア", types: ["Shrine","Hebra","Cold Resistance"] },
    { name: "オルディンの塔の祠3つクリア", types: ["Shrine","Eldin"] },
    { name: "ほこらチャレンジ:大蛇 喰らいし龍", types: ["Shrine","Shrine Quest","Lake","Dragon"] },
    { name: "ほこらチャレンジ:ガマンくらべ", types: ["Shrine","Shrine Quest","Gerudo"] },
    { name: "ガチロックを倒す", types: ["Rupee","Gems","Miniboss","Talus","Cold Resistance"] },
    { name: "ガーディアン（砲台型）", types: ["Miniboss","Guardian","Hyrule Castle"] },
    { name: "ハイラル図鑑の生き物を5つ埋める", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑の魔物を5つ埋める", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑の武器を5つ埋める", types: ["Camera","Compendium"] },
    { name: "シドとツーショット写真を撮る", types: ["Lanayru","Camera"] },
    { name: "オルドラから素材を入手", types: ["Dragon"] },
    { name: "盾サーファーの初級コースをクリア", types: ["Minigame","Hebra","Cold Resistance"] },
    { name: "スノーブーツ", types: ["Clothes","Boots","Side Quest","Gerudo","Camera"] },
    { name: "マグロックを倒す", types: ["Rupee","Gems","Miniboss","Talus","Eldin"] }
];
bingoList[14] = [
    { name: "コログのミ25個", types: ["Korok"] },
    { name: "フィローネの塔のコログのミ12個", types: ["Korok","Faron"] },
    { name: "ゲルドの塔のコログのミ9つ", types: ["Korok","Gerudo"] },
    { name: "タバンタの塔のコログのミ12個", types: ["Korok","Tabantha"] },
    { name: "森林の塔のコログのミ12個", types: ["Korok","Woodland"] },
    { name: "アッカレの塔のコログのミ12個", types: ["Korok","Akkala"] },
    { name: "ラネールの塔のコログのミ12個", types: ["Korok. Lanayru"] },
    { name: "マーロンの泉を解放する", types: ["Lake","Rupee"] },
    { name: "ミニチャレンジ:宝石はお好き？", types: ["Side Quest","Wasteland","Gems"] },
    { name: "ゾーラの兜 ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos"] },
    { name: "夜行マスク", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "夜光スーツ", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "夜光タイツ", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "トパーズの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:寒いときにはカレーを！", types: ["Side Quest","Tabantha","Eldin"] },
    { name: "祠10つクリア", types: ["Shrine"] },
    { name: "ゲルドの塔の祠3つクリア", types: ["Shrine","Gerudo","Cold Resistance"] },
    { name: "ほこらチャレンジ:石碑のかけら探し", types: ["Shrine","Shrine Quest","Faron","Camera"] },
    { name: "記憶を2つ思い出す", types: ["Camera"] },
    { name: "黒ヒノックスを倒す", types: ["Miniboss","Hinox"] },
    { name: "スタルヒノックスを倒す", types: ["Miniboss","Hinox"] },
    { name: "ガーディアン（飛行型）を倒す", types: ["Miniboss","Guardian"] },
    { name: "がんばりの器3つ", types: ["Shrine","Stamina"] },
    { name: "ネルドラから素材を入手", types: ["Hateno","Cold Resistance","Dragon"] },
    { name: "リモコンバクダン+", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "塔を4つ起動", types: ["Tower"] },
    { name: "ミニチャレンジを11個クリア", types: ["Side Quest"] }
];
bingoList[15] = [
    { name: "荒野の塔のコログのミ12個", types: ["Korok","Wasteland"] },
    { name: "リトの羽毛服 ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "リトの羽毛ズボン ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "リト装備一式", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Tabantha"] },
    { name: "耐火の石靴 ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "クライムシューズ ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "サファイアの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ルビーの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ボコブリンマスク", types: ["Clothes","Kilton"] },
    { name: "ミニチャレンジ:デスマウンテンの秘密", types: ["Side Quest","Eldin"] },
    { name: "ミニチャレンジ:ライネル調査", types: ["Side Quest","Lanayru","Camera","Zora Gear"] },
    { name: "ミニチャレンジ:ハイラル城に眠る武器", types: ["Side Quest","Hyrule Castle"] },
    { name: "ほこらチャレンジ:野生の試練", types: ["Shrine","Shrine Quest","Faron"] },
    { name: "ほこらチャレンジ:巨人三人兄弟の秘密", types: ["Shrine","Shrine Quest","Faron","Hinox"] },
    { name: "ほこらチャレンジ:おっきな山のおっきな木", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance"] },
    { name: "ほこらチャレンジ:断崖の試練", types: ["Shrine","Shrine Quest","Hebra","Cold Resistance","Barbarian Gear"] },
    { name: "風斬り刀", types: ["Equipment","Wasteland"] },
    { name: "ライネルを倒す", types: ["Miniboss","Lynel"] },
    { name: "モルドラジークを倒す", types: ["Miniboss","Molduga","Wasteland"] },
    { name: "ハートの器6つ", types: ["Shrine","Heart"] },
    { name: "ルージュとツーショット写真を撮る", types: ["Wasteland","Camera"] },
    { name: "燃えながら自撮り", types: ["Eldin","Camera"] },
    { name: "ビタロック+", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "ハイラル図鑑の武器10個埋める", types: ["Camera","Compendium"] }
];
bingoList[16] = [
    { name: "双子山の塔のコログのミ15個", types: ["Korok","Dueling Peaks"] },
    { name: "平原の塔のコログのミ15個", types: ["Korok","Central Hyrule"] },
    { name: "英傑の服 ★", types: ["Clothes","Champion","Camera","Great Fairy"] },
    { name: "雪よけの羽飾り ★", types: ["Clothes","Snow Gear","Cold Resistance","Rupee","Great Fairy"] },
    { name: "ラバー装備一式", types: ["Clothes","Rubber Gear","Faron","Ridgeland"] },
    { name: "耐火の石鎧 ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "オパールの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:モルドラジークの肝", types: ["Side Quest","Wasteland","Molduga"] },
    { name: "ミニチャレンジ:免許皆伝への道", types: ["Side Quest","Eldin","Talus"] },
    { name: "ミニチャレンジ:小さな妹の大きな願い", types: ["Side Quest","Akkala"] },
    { name: "ミニチャレンジ:ぴかぴかのルミーしれん", types: ["Side Quest","Wasteland","Camera"] },
    { name: "ミニチャレンジを12個クリア", types: ["Side Quest"] },
    { name: "ハイラル図鑑の生き物を10個埋める", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑の魔物を10個埋まる", types: ["Camera","Compendium"] }
];
bingoList[17] = [
    { name: "ハテノの塔のコログのミ15個", types: ["Korok","Hateno"] },
    { name: "湖のコログのミ15個", types: ["Korok","Lake"] },
    { name: "ゲルドのコログのミ12個", types: ["Korok","Gerudo"] },
    { name: "丘陵のコログのミ15個", types: ["Korok","Ridgeland"] },
    { name: "ヘブラのコログのミ12個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンのコログのミ12個", types: ["Korok","Eldin"] },
    { name: "熱砂の鉢がね ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "熱砂の肩当て ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "熱砂のズボン ★", types: ["Clothes","Desert Gear","Wasteland","Rupee","Great Fairy"] },
    { name: "サンドブーツ", types: ["Clothes","Boots","Side Quest","Gerudo"] },
    { name: "ミニチャレンジ:八人目の英雄", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "祠を11つクリア", types: ["Shrine"] },
    { name: "ほこらチャレンジを5つクリア", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:ガーディアンを見たい", types: ["Shrine","Shrine Quest","Lake","Camera","Guardian"] },
    { name: "ほこらチャレンジ:力の泉の言い伝え", types: ["Shrine","Shrine Quest","Akkala","Dragon"] },
    { name: "”ライネル”と名の付いた装備", types: ["Equipment","Lynel"] },
    { name: "炎、氷、雷属性の武器各１つ", types: ["Equipment"] },
    { name: "飛行訓練場の的当てで20点以上", types: ["Minigame","Tabantha","Cold Resistance"] },
    { name: "塔を5つ起動", types: ["Tower"] },
    { name: "ハイラル図鑑の武器を15個埋める", types: ["Camera","Compendium"] }
];
bingoList[18] = [
    { name: "ハイラル図鑑の生き物を15個埋める", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑の魔物を15個埋める", types: ["Camera","Compendium"] },
    { name: "コログのミ30個", types: ["Korok"] },
    { name: "フィローネの塔のコログのミ15個", types: ["Korok","Faron"] },
    { name: "アッカレの塔のコログのミ15個", types: ["Korok","Akkala"] },
    { name: "ラネールの塔のコログのミ15個", types: ["Korok. Lanayru"] },
    { name: "熱砂の装備一式", types: ["Clothes","Desert Gear","Wasteland","Rupee"] },
    { name: "耐火の石兜 ★", types: ["Clothes","Flame Gear","Eldin","Rupee","Great Fairy"] },
    { name: "ゾーラのすねあて ★", types: ["Clothes","Zora Gear","Great Fairy","Lizalfos","Camera"] },
    { name: "夜光マスク ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "スノーブーツ ★", types: ["Clothes","Boots","Side Quest","Great Fairy","Camera"] },
    { name: "ミニチャレンジ:解放 さらなる力", types: ["Side Quest","Hateno","Camera"] },
    { name: "ミニチャレンジ:求ム！不審者情報", types: ["Side Quest","Akkala","Kilton","Camera"] },
    { name: "祠を12つクリア", types: ["Shrine"] },
    { name: "ほこらチャレンジ:ラネール山のお宝を探れ！", types: ["Shrine","Shrine Quest","Hateno","Cold Resistance","Dragon"] },
    { name: "記憶を3つ思い出す", types: ["Camera"] },
    { name: "ハイリアの盾", types: ["Miniboss","Hinox","Hyrule Castle"] },
    { name: "山のヌシ（サトリ）に乗る", types: ["Horse","Ridgeland","Stamina"] },
    { name: "家を買う", types: ["Hateno","Rupee"] },
    { name: "力の試練 極位の祠をクリア", types: ["Shrine","Guardian"] }
];
bingoList[19] = [
    { name: "荒野の塔のコログのミ15個", types: ["Korok","Wasteland"] },
    { name: "タバンタのコログのミ15個", types: ["Korok","Tabantha"] },
    { name: "森林の塔のコログのミ15個", types: ["Korok","Woodland"] },
    { name: "夜光スーツ ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "夜光タイツ ★", types: ["Clothes","Radiant Gear","Rupee","Gems","Great Fairy"] },
    { name: "コハクの耳飾り ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ミニチャレンジ:骨の馬の絵", types: ["Side Quest","Hebra","Camera"] },
    { name: "ほこらチャレンジ:盗まれた宝珠", types: ["Shrine","Shrine Quest","Dueling Peaks","Heirloom","Camera"] },
    { name: "ほこらチャレンジ:弟はいずこ？", types: ["Shrine","Shrine Quest","Eldin"] },
    { name: "神獣を1体解放する", types: ["Divine Beast"] },
    { name: "メインチャレンジ:風の神獣ヴァ・メドー", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "リーバルトルネード", types: ["Divine Beast","Tabantha","Cold Resistance"] },
    { name: "闘技場のライネルを倒す", types: ["Miniboss","Lynel","Central Hyrule"] },
    { name: "塔を6つ起動", types: ["Tower"] },
    { name: "ミニチャレンジ13個クリア", types: ["Side Quest"] },
    { name: "クライムグローブ", types: ["Clothes","Climbing Gear","Hateno"] }
];
bingoList[20] = [
    { name: "ゲルドの塔のコログのミ15個", types: ["Korok","Gerudo"] },
    { name: "ヘブラの塔のコログのミ15個", types: ["Korok","Hebra","Cold Resistance"] },
    { name: "オルディンの塔のコログのミ15個", types: ["Korok","Eldin"] },
    { name: "ゾーラの装備一式", types: ["Clothes","Zora Gear","Lanayru","Camera"] },
    { name: "蛮族の兜 ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "蛮族の服 ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "トパーズの耳飾り ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ダイヤの耳飾り", types: ["Clothes","Gems","Rupee","Wasteland"] },
    { name: "ミニチャレンジ:忘れられた剣", types: ["Side Quest","Wasteland","Gerudo","Boots","Cold Resistance","Camera"] },
    { name: "ミニチャレンジ:キールを探して！", types: ["Side Quest","Tabantha"] },
    { name: "ミニチャレンジ:宝石インポーター", types: ["Side Quest","Eldin","Gems"] },
    { name: "ミニチャレンジ:もう一人の研究者", types: ["Side Quest","Akkala","Camera"] },
    { name: "ほこらチャレンジ6つクリア", types: ["Shrine","Shrine Quest"] },
    { name: "メインチャレンジ:水の神獣 ヴァ・ルッタ", types: ["Divine Beast","Lanayru"] },
    { name: "ミファーの祈り", types: ["Divine Beast","Lanayru"] },
    { name: "記憶を4つ思い出す", types: ["Camera"] },
    { name: "がんばりの器4つ", types: ["Shrine","Stamina"] },
    { name: "ハイラル図鑑の武器を20個埋める", types: ["Camera","Compendium"] }
];
bingoList[21] = [
    { name: "ハイラル図鑑の生き物を20個埋める", types: ["Camera","Compendium"] },
    { name: "ハイラル図鑑の魔物を20個埋める", types: ["Camera","Compendium"] },
    { name: "コログのミ35個", types: ["Korok"] },
    { name: "大妖精を3人解放する", types: ["Rupee","Great Fairy"] },
    { name: "耐火の装備一式", types: ["Clothes","Flame Gear","Eldin","Rupee"] },
    { name: "蛮族の腰巻き ★", types: ["Clothes","Barbarian Gear","Great Fairy","Lynel"] },
    { name: "夜光装備一式", types: ["Clothes","Radiant Gear","Rupee","Gems","Wasteland"] },
    { name: "オパールの耳飾り ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "サファイアの耳飾り ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "ルビーの耳飾り ★", types: ["Clothes","Gems","Rupee","Great Fairy"] },
    { name: "祠を13つクリア", types: ["Shrine"] },
    { name: "ほこらチャレンジ7つクリア", types: ["Shrine","Shrine Quest"] },
    { name: "ほこらチャレンジ:うるわしの美酒を求めて", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "ほこらチャレンジ:リトの兄弟岩", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "ほこらチャレンジ:リトの詩の謎", types: ["Shrine","Shrine Quest","Tabantha"] },
    { name: "記憶を5つ思い出す", types: ["Camera"] },
    { name: "ボヨーンハンマー", types: ["Equipment","Kilton"] },
    { name: "ハートの器7つ", types: ["Shrine","Heart"] },
    { name: "全てのシーカーアイテムをアップグレードする", types: ["Camera","Rune Upgrade","Hateno"] },
    { name: "ほこらチャレンジ:英傑祭の詩", types: ["Shrine","Shrine Quest","Lanayru"] }
];
bingoList[22] = [
    { name: "ミニチャレンジ:ハイラルのなぞなぞしれん", types: ["Side Quest","Woodland","Lynel"] },
    { name: "ミニチャレンジ:雨ときどきカエル", types: ["Side Quest","Lanayru"] },
    { name: "ミニチャレンジ:夜光石収集", types: ["Side Quest","Lanayru","Gems"] },
    { name: "ミニチャレンジ:流された嫁", types: ["Side Quest","Lanayru"] },
    { name: "祠を14つクリア", types: ["Shrine"] },
    { name: "ほこらチャレンジを8つクリア", types: ["Shrine","Shrine Quest"] },
    { name: "塔を7起動する", types: ["Tower"] },
    { name: "ミニチャレンジ14個クリア", types: ["Side Quest"] }
];
bingoList[23] = [
    { name: "コログのミ40個", types: ["Korok"] },
    { name: "ミニチャレンジ:ブリザー谷のガチロック", types: ["Side Quest","Tabantha","Hebra","Cold Resistance"] },
    { name: "ミニチャレンジ:ラルス池の巨人討伐", types: ["Side Quest","Lanayru","Hinox"] },
    { name: "祠を15つクリア", types: ["Shrine"] },
    { name: "メインチャレンジ:炎の神獣 ヴァ・ルーダニア", types: ["Divine Beast","Eldin"] },
    { name: "ダルケルの護り", types: ["Divine Beast","Eldin"] },
    { name: "記憶を6つ思い出す", types: ["Camera"] },
    { name: "英傑の武器か盾を作り直す", types: ["Equipment","Divine Beast","Gems"] },
    { name: "クライムグローブ ★", types: ["Clothes","Climbing Gear","Great Fairy"] },
    { name: "塔を8つ起動する", types: ["Tower"] }
];
bingoList[24] = [
    { name: "コログのミ45個", types: ["Korok"] },
    { name: "ミニチャレンジ:巨大クジラの化石", types: ["Side Quest","Camera"] },
    { name: "祠を16つクリア", types: ["Shrine"] },
    { name: "メインチャレンジ:雷の神獣 ヴァ・ナボリス", types: ["Divine Beast","Wasteland"] },
    { name: "ウルボザの怒り", types: ["Divine Beast","Wasteland"] },
    { name: "ガノンを倒す", types: ["Hyrule Castle"] },
    { name: "塔を9つ起動する", types: ["Tower"] },
    { name: "クライム装備一式", types: ["Clothes","Climbing Gear"] }
];
bingoList[25] = [
    { name: "コログのミ50個", types: ["Korok"] },
    { name: "ミニチャレンジ:ゾーラの石碑を探して", types: ["Side Quest","Lanayru"] },
    { name: "神獣を2体解放する", types: ["Divine Beast"] },
    { name: "ミニチャレンジ:バレッタを探して", types: ["Side Quest","Wasteland"] },
    { name: "ミニチャレンジ:犯人は誰だ！", types: ["Side Quest","Wasteland"] },
    { name: "ほこらチャレンジ:無敗の女王", types: ["Shrine","Shrine Quest","Wastelands"] },
    { name: "塔を10つ起動する", types: ["Tower"] },
    { name: "ミニチャレンジ15個クリアする", types: ["Side Quest"] },
    { name: "蛮族の装備一式", types: ["Clothes","Barbarian Gear"] }
];
$(function() { srl.bingo(bingoList, 5); });